apiVersion: v1
data:
  password: {{ .Values.cnpg.app.password | b64enc}}
  username: {{ .Values.cnpg.app.username | b64enc}}
kind: Secret
metadata:
  name: {{ .Values.cnpg.name}}-app-secret
type: kubernetes.io/basic-auth