apiVersion: v1
data:
  password: {{ .Values.cnpg.superuser.password | b64enc}}
  username: {{ .Values.cnpg.superuser.username | b64enc}}
kind: Secret
metadata:
  name: {{ .Values.cnpg.name}}-superuser-secret
type: kubernetes.io/basic-auth